### ISSUE TITLE
The zip file cannot be opened because it is invalid error Windows 10

### ISSUE THREAD

**Issue by Joey-Destroyah** [tylerraiz/EDBMods#6]

**Comment by Joey-Destroyah** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/62820134/131179343-9340b716-0a8a-4ede-971d-be95fdee8371.png)

**Comment by Joey-Destroyah** [comment]
On the release, the folder opened fine.

**Comment by tylerraiz** [comment]
I don't know what the problem is, but you shouldn't try to download the
release branch in this case, but use one of the pre-packaged releases here:
https://github.com/tylerraiz/EDBMods/releases.
