### ISSUE TITLE
RO parts have wierd pink texture, and in some cases are non functional

### ISSUE THREAD

**Issue by Joey-Destroyah** [tylerraiz/EDBMods#7]
![Screenshot (9)](https://user-images.githubusercontent.com/62820134/131255114-c101af76-65b0-4238-8998-9a6f4655f1eb.png)
![Screenshot (10)](https://user-images.githubusercontent.com/62820134/131255115-5f1e3e1b-cfcf-49bc-9e3a-bfd33abe28a4.png)
![Screenshot (5)](https://user-images.githubusercontent.com/62820134/131255119-7710ca37-4675-407d-bd18-51210aaf0076.png)
![Screenshot (6)](https://user-images.githubusercontent.com/62820134/131255122-7c60b589-2ac2-424b-bf9d-365089e25e70.png)
![Screenshot (7)](https://user-images.githubusercontent.com/62820134/131255124-91563db3-d9e2-480f-a6c4-4241e4226e69.png)
![Screenshot (2)](https://user-images.githubusercontent.com/62820134/131255126-8fdcb229-86ec-400b-9570-f9961c296737.png)
![Screenshot (3)](https://user-images.githubusercontent.com/62820134/131255128-40e56bcb-e150-4765-b0fc-a14fa6e61500.png)

**Comment by tylerraiz** [comment]
None of the ones you showed are my parts.

**Comment by tylerraiz** [comment]
From your GameData, it doesn't even look like you have my mods installed at all.

**Comment by Joey-Destroyah** [comment]
Wrong screenshot
![Screenshot (12)](https://user-images.githubusercontent.com/62820134/131526420-0c664b36-3973-4246-9172-8fbdc1938ad7.png)

**Comment by tylerraiz** [comment]
Those pink parts are still not mine, and my parts won't interact with them
in any way.

**Comment by Joey-Destroyah** [comment]
Don't know what the cause is then. Might be texturesunlimited.
