### ISSUE TITLE
Boca chica terrains not working

### ISSUE THREAD

**Issue by Inmune4** [tylerraiz/EDBMods#9]
Hi! As a user of RO 17.12 and ksp 1.12.3, when I tried to download boca chica terrains and loaded them to my gamedata folder, they didn't load onto the game, thus not showing in game. My ksp is pretty clean, I have only dependency mods for RO and pekka's starship, so no mods that could interfere with that. I have ksc switcher and kerbal konstructs, yet it isn't showing. My rss quality download is max so, and as I've herad at your videos, it should work. Any idea on how to help? thanks!
![Captura de pantalla 2024-09-20 183435](https://github.com/user-attachments/assets/bd6c5f3a-ebdd-4b10-a687-96c94497de39)
![Captura de pantalla 2024-09-20 183332](https://github.com/user-attachments/assets/780c7aec-990e-4b6c-ac62-2d09b5de38fa)
![Captura de pantalla 2024-09-20 183201](https://github.com/user-attachments/assets/f265108e-d383-4d02-a9d0-5d512ea9822d)

**Comment by PEKKA-Space** [comment]
You need to actually switch your launchsite to boca chica. Also this is the wrong mod to complain about you need to go to: https://github.com/tylerraiz/Terrains/issues

**Comment by Inmune4** [comment]
I feel so dumb man 😭
anyways thanks a lot for helping with this pekka! Pleasure talking to u

**Comment by Inmune4** [comment]
thanks for both the help and the mod, pekka
